name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["312", "313"]
        os: ["ubuntu-latest", "ubuntu-24.04-arm", "macos-14"]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: daniel-fahey
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      
      - name: Run Nix flake check
        run: nix flake check
      
      - name: Run CI checks for Python ${{ matrix.python-version }}
        run: nix develop .#py${{ matrix.python-version }} --command bash -c "make ci"

  publish:
    name: Build and publish Python distribution
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    
    environment:
      name: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
      url: https://${{ github.event_name == 'release' && 'pypi.org' || 'test.pypi.org' }}/p/markmap-anywidget
      
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: daniel-fahey
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build sdist and wheel
        run: nix develop .#py313 --command bash -c "make build"

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ github.event_name == 'release' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
          skip-existing: true
          verbose: true
