name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-test:
    name: Build & Test on Python ${{ matrix.python-version }} 🏗️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["310", "311", "312", "313"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: daniel-fahey
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build and test
        run: nix develop .#py${{ matrix.python-version }} --command bash -c "make all"
      - name: Upload distribution packages
        if: matrix.python-version == '313'
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 1

  publish:
    name: Publish to PyPI/TestPyPI 📦
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    
    environment:
      name: ${{ github.event_name == 'release' && 'pypi' || 'testpypi' }}
      url: ${{ github.event_name == 'release' && 'https://pypi.org/p/markmap-anywidget' || 'https://test.pypi.org/p/markmap-anywidget' }}

    permissions:
      id-token: write

    steps:
      - name: Download distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI/TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ github.event_name == 'release' && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
          skip-existing: false
          verbose: true
